version: '3.4'

services:
  dsrnetschool_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_dsrnetschool_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  dsrnetschool_redis:
    ports:
      - '6379:6379'
    networks:
      - shared_dsrnetschool_net
    volumes:      
      - ~/.docker-conf/redis/data/:/data

  dsrnetschool_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_dsrnetschool_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq

  dsrnetschool_api:
    ports:
      - "10000:80"
    networks:
      - shared_dsrnetschool_net
    env_file:
      - env.api
      
  dsrnetschool_identity:
    ports:
      - "10001:80"
    networks:
      - shared_dsrnetschool_net
    env_file:
      - env.identity

  dsrnetschool_worker_1:
    networks:
      - shared_dsrnetschool_net
    env_file:
      - env.worker

  dsrnetschool_worker_2:
    networks:
      - shared_dsrnetschool_net
    env_file:
      - env.worker

  dsrnetschool_web:
    ports:
      - "10002:80"
    networks:
      - shared_dsrnetschool_net

networks:
  shared_dsrnetschool_net:
    name: dsr_net_school
    driver: bridge